[versions]
ajalt-clikt = "5.0.3"
kotlinx-datetime = "0.7.1"
kotlinx-io = "0.8.0"
okhttp="4.12.0"
pdvrieze-xmlutil = "0.91.2"

[libraries]
ajalt-clikt = { group = "com.github.ajalt.clikt", name = "clikt", version.ref = "ajalt-clikt" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-io-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
pdvrieze-xmlutil-core = { group = "io.github.pdvrieze.xmlutil", name = "core", version.ref = "pdvrieze-xmlutil"}
pdvrieze-xmlutil-serialization = { group = "io.github.pdvrieze.xmlutil", name = "serialization", version.ref = "pdvrieze-xmlutil"}
